id: P1197EC71
initial_creation_type: input
source_metadata:
  title: Drimé Ösal Lingpa Series
  language: de
  description: 'Texts by and about Tertön Drimé Ösal Lingpa (dri med ''od gsal gling
    pa):'
  volume:
    fdad86b220ed48b19c9b0a3e6243240a:
      title: The Seeds of Faith, A Prayer to the Vidyādhara and Great Tertön Lerab
        Lingpa
      parent: Prayers
created_at: '2022-02-28T23:04:53.523813'
last_modified_at: '2022-02-28T23:04:53.523817'
